//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopMvcDBContainer : DbContext
    {
        public ShopMvcDBContainer()
            : base("name=ShopMvcDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Client> ClientSet { get; set; }
        public DbSet<Manager> ManagerSet { get; set; }
        public DbSet<User> UserSet { get; set; }
        public DbSet<User1> User1Set { get; set; }
        public DbSet<User2> User2Set { get; set; }
        public DbSet<Order> OrderSet { get; set; }
        public DbSet<Item> ItemSet { get; set; }
    }
}
